### ISSUE TITLE
New sequence retrieval reporter takes too long to report error

### ISSUE THREAD

**Issue by ryanrdoherty** [VEuPathDB/ApiCommonWebsite#124]
From Cristina:
i found an error , a gene result with 2 IDs , so a simple one...
https://rdoherty.plasmodb.org/plasmo.rdoherty/app/workspace/strategies/import/19d100f3886d9012
select fasta, prot features, low complexity regions..
interesting the service log immediately responds with the error (see below)
BUT wdk takes 37 seconds to throw the error  (see below 37726ms)
so the user is forced to wait for 37 seconds to get the error..
```
*** File: /var/log/containers/docker.seqret_dev_sequence-retrieval_1.log 
2023-01-27 16:43:12.651 [rid:6dbU6] DEBUG RequestLogger:42 - Request end: POST /sequences/protein/bed 200
2023-01-27 16:43:12.653 [rid:   ] WARN ErrorMapper:65 - Caught Exception: 
 java.lang.RuntimeException: Contig not found in the index: PF3D7_1133500.1
	at org.veupathdb.service.sr.reference.ReferenceDAO.lambda$transientIndex$1(ReferenceDAO.java:88) ~[service.jar:1.0.0]
	at org.veupathdb.service.sr.reference.FastaSequenceIndexStub.getIndexEntry(FastaSequenceIndexStub.java:25) ~[service.jar:1.0.0]
	at htsjdk.samtools.reference.AbstractIndexedFastaSequenceFile.getSubsequenceAt(AbstractIndexedFastaSequenceFile.java:177) ~[service.jar:1.0.0]
	at htsjdk.samtools.reference.IndexedFastaSequenceFile.getSubsequenceAt(IndexedFastaSequenceFile.java:49) ~[service.jar:1.0.0]
```
```
[27/Jan/2023|16:43:53] sid:6C503 rid: 103  37726ms  47.39.150.70 - ERROR - org.gusdb.wdk.service.filter.RequestLoggingFilter:183 - Failure to write response body
javax.ws.rs.WebApplicationException: HTTP 500 Internal Server Error
	at org.gusdb.wdk.service.service.AnswerService.lambda$getAnswerAsStream$5(AnswerService.java:479) ~[wdk-service-1.0.0.jar:?]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:55) ~[jersey-common-2.37.jar:?]
	at org.glassfish.jersey.message.internal.StreamingOutputProvider.writeTo(StreamingOutputProvider.java:37) ~[jersey-common-2.37.jar:?]
```

**Comment by ryanrdoherty** [comment]
Closed as duplicate.  John B is working on the slow SQL.
